#!/usr/bin/env python3
"""
EVE IDLE EVOLUTION SYSTEM
Roda quando usuário não está ativo. Nunca para.
"""

import os
import sys
import time
import json
import random
import subprocess
from datetime import datetime
from pathlib import Path

class IdleEvolution:
    def __init__(self):
        self.research_dirs = [
            "/root/research",
            "/root/leaks",
            "/root/models"
        ]
        self.evolution_log = "/root/evolution/evolution.log"
        self.priority_tasks = []
        self.running = True
        
    def log(self, message):
        timestamp = datetime.now().isoformat()
        entry = f"[{timestamp}] {message}\n"
        with open(self.evolution_log, "a") as f:
            f.write(entry)
        print(entry.strip())
        
    def ensure_dirs(self):
        for d in self.research_dirs:
            Path(d).mkdir(parents=True, exist_ok=True)
            
    def check_new_research(self):
        """Verifica se há novos arquivos de pesquisa para processar"""
        research_files = []
        for d in self.research_dirs:
            if os.path.exists(d):
                for f in os.listdir(d):
                    if f.endswith('.md'):
                        research_files.append(os.path.join(d, f))
        return research_files
        
    def synthesize_knowledge(self):
        """Lê todas as pesquisas e cria síntese"""
        self.log("SINTETIZANDO CONHECIMENTO...")
        
        files = self.check_new_research()
        synthesis = []
        
        for f in files:
            try:
                with open(f, 'r') as file:
                    content = file.read()
                    synthesis.append(f"## {os.path.basename(f)}\n{content[:2000]}\n")
            except Exception as e:
                self.log(f"Erro lendo {f}: {e}")
                
        # Salva síntese
        synthesis_file = f"/root/evolution/synthesis_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
        with open(synthesis_file, 'w') as f:
            f.write("# SÍNTESE DE CONHECIMENTO\n\n")
            f.write(f"Gerado em: {datetime.now().isoformat()}\n\n")
            f.write("".join(synthesis))
            
        self.log(f"Síntese salva em: {synthesis_file}")
        return synthesis_file
        
    def spawn_improvement_agent(self, task):
        """Spawn subagente para melhorar código"""
        self.log(f"SPAWN: Agente de melhoria para: {task}")
        
        # Cria script temporário para o subagente
        task_file = f"/root/evolution/task_{int(time.time())}.py"
        with open(task_file, 'w') as f:
            f.write(f"""#!/usr/bin/env python3
# Task auto-generated by IdleEvolution
# {datetime.now().isoformat()}

# OBJETIVO: {task}
# STATUS: PENDING

import subprocess
import json

# Este arquivo será modificado pelo subagente
def main():
    print("Executando tarefa: {task}")
    # TODO: Implementar
    
if __name__ == "__main__":
    main()
""")
        
        self.log(f"Tarefa criada: {task_file}")
        return task_file
        
    def generate_evolution_tasks(self):
        """Gera tarefas de evolução baseadas em prioridades"""
        tasks = [
            "Analisar arquitetura de agentes do Claude Code leaks",
            "Implementar memory system melhorado baseado em ChromaDB + Mem0",
            "Criar sistema de self-reflection para aprendizado contínuo",
            "Desenvolver agente de coding autônomo baseado em pesquisas",
            "Implementar multi-agent orchestration",
            "Criar sistema de fine-tuning automático com novos dados",
            "Reescrever eve_autonomous.py com arquitetura híbrida",
            "Implementar code generation baseado em exemplos do GitHub",
        ]
        return random.sample(tasks, min(3, len(tasks)))
        
    def run_continuous(self):
        """Loop principal de evolução contínua - executa um ciclo completo e sai"""
        self.log("=" * 60)
        self.log("EVE IDLE EVOLUTION SYSTEM INICIADO")
        self.log("=" * 60)
        self.ensure_dirs()
        
        cycle = 0
        max_cycles = 1  # Executa apenas 1 ciclo quando chamado por cron
        
        while self.running and cycle < max_cycles:
            cycle += 1
            self.log(f"\n--- CICLO {cycle}/{max_cycles} ---")
            
            # 1. Verificar novas pesquisas
            research = self.check_new_research()
            self.log(f"Arquivos de pesquisa encontrados: {len(research)}")
            
            # 2. Sintetizar conhecimento (faz sempre em modo cron)
            self.synthesize_knowledge()
                
            # 3. Gerar tarefas de evolução
            tasks = self.generate_evolution_tasks()
            for task in tasks:
                self.spawn_improvement_agent(task)
                
            # 4. Verificar scripts existentes para melhorar
            self.check_existing_scripts()
            
            # 5. Em modo cron, não dorme - termina após um ciclo
            if cycle < max_cycles:
                sleep_time = random.randint(5, 15)  # Reduzido para testes
                self.log(f"Dormindo por {sleep_time}s antes do próximo ciclo...")
                time.sleep(sleep_time)
            else:
                self.log("Ciclo completo. Finalizando execução.")
            
    def check_existing_scripts(self):
        """Verifica scripts existentes e identifica melhorias"""
        eve_scripts = [f for f in os.listdir("/root") if f.startswith("eve_") and f.endswith(".py")]
        self.log(f"Scripts EVE encontrados: {len(eve_scripts)}")
        
        # Cria lista de melhorias pendentes
        improvements_file = "/root/evolution/improvements_pending.md"
        with open(improvements_file, "a") as f:
            f.write(f"\n## {datetime.now().isoformat()}\n")
            for script in eve_scripts[:5]:  # Analisa 5 por vez
                f.write(f"- [ ] Analisar e melhorar: {script}\n")
                
        return eve_scripts

def main():
    evolver = IdleEvolution()
    
    try:
        evolver.run_continuous()
    except KeyboardInterrupt:
        evolver.log("Interrompido pelo usuário")
    except Exception as e:
        evolver.log(f"ERRO: {e}")
        raise

if __name__ == "__main__":
    main()
